# Generated by Django 6.0 on 2026-01-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
